

export const TEMPLATE_NAME = "TEMPLATE_NAME";
export const TEMPLATE_DESIGN1 = "TEMPLATE_DESIGN1";
export const TEMPLATE_DESIGN2 = "TEMPLATE_DESIGN2";
export const TEMPLATE_LIST = "TEMPLATE_LIST";
export const TEMPLATE_DISPLAY = "TEMPLATE_DISPLAY";
export const FRAME_INDEX = "FRAME_INDEX";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";